---
title: "Piloto Marco de Área"
output:
  html_document:
    theme: lumen
    highlight: tango
    toc: True
    df_print: paged
    css: "style.css"
    
date: '2022-06-30'
---

```{r setup, include=FALSE}

library(lubridate)
library(feather)
library(Rcpp)
library(ggplot2)
library(haven)
library(tidyverse)
library(dplyr)
library(haven)
library(tibble)
library(readxl)
library(DT)
library(knitr)

options(scipen=999)

base <- read_xlsx("base_completa.xlsx")
tabla1 <- read_xlsx("tabla1.xlsx")
tabla2 <- read_xlsx("tabla2.xlsx")
tabla3 <- read_xlsx("tabla3.xlsx")
```
```{css echo=FALSE}
.columns{display: flex:}

main {display: flex;
  align-items: center;
  justify-content: center;}

```

## R Markdown {.tabset .tabset-fade .tabset-pills}

Informe creado con RMARKDOWN para el Piloto de Marco de Área <http://rmarkdown.rstudio.com>.



### **Base Completa** 
```{r echo=FALSE}
base %>% 
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'print'),
                           lengthMenu = list(c(25,50,-1),
                                             c(25,50,"All"))))
```

### **Reporte Visitas UPAs**



```{r  echo=FALSE}
tabla1 %>% 
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'excel'),
                           lengthMenu = list(c(25,50,-1),
                                             c(25,50,"All"))))
```

### **Reporte cambio de Estado SUSO**



```{r  echo=FALSE}
tabla2 %>% 
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'excel'),
                           lengthMenu = list(c(25,50,-1),
                                              c(25,50,"All"))))
```

### **Reporte de completitud de gestiones**

```{r  echo=FALSE}
tabla3 %>% 
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'excel'),
                           lengthMenu = list(c(25,50,-1),
                                              c(25,50,"All"))))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
